services:
  backend:
    build:
      context: ./MinaGroup.Backend
    ports:
      - "5000:8080"
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_PORT=${SQL_PORT}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_NAME=${DB_NAME}
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - TZ=Europe/Copenhagen
    depends_on:
      - ${DB_HOST}
    restart: always

  minagroup-db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: